Algoritmo "teste"

Var

     idade :inteiro
     salario1,salario2 :real
     nome : caractere
Inicio

 escreva(" digite seu nome : ")
 leia (nome)
 escreva("digite sua idade:")
 leia(idade)
 escreva("digite quanto vc ganhou nos ultimos meses")
 leia(salario1)
 leia(salario2)
 
 
 escreval("DADOS DIGITADOS:")
 escreval("nome : " , nome)
 escreval("idade :" , idade )
 escreval("salario 1:" ,salario1:8:2)
 escreval("salario 2: ",salario2:8:2)

Fimalgoritmo