Algoritmo "estrutura_enquanto"

Var
    x , y : inteiro

Inicio
    escreval("DIGITE DOIS NUMEROS :")
    leia(x)
    leia(y)
    
    enquanto x<>y faca
    
       se x < y entao
          escreval("CRESCENTE")
       senao
           escreval("DECRESCENTE")
       fimse
       
       escreval(" DIGITE OUTROS NUMEROS:")
       leia(x)
       leia(y)
       
    fimenquanto




Fimalgoritmo