Algoritmo "troco"


Var

preco:real
quantidade :inteiro
dinheiro:real
troco:real


Inicio

    escreva("Preco unitario do produto :")
    leia(preco)
    escreva("Quantidade comprada : ")
    leia(quantidade)
    escreva("dinheiro recebido : ")
    leia(dinheiro)
    
    troco <- dinheiro - preco * quantidade
    
    escreval("troco = ",troco:8:2)

 
 
 


 

Fimalgoritmo